"""feat: new media table

Revision ID: 131be2b4cb78
Revises: 8c1988974200
Create Date: 2026-04-08 08:54:18.671220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '131be2b4cb78'
down_revision: Union[str, Sequence[str], None] = '8c1988974200'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog_medias',
    sa.Column('media_id', sa.Integer(), nullable=False),
    sa.Column('blog_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('media_type', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('storage_key', sa.String(), nullable=False),
    sa.Column('mime_type', sa.String(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['blog_id'], ['blogs.blog_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('media_id')
    )
    op.create_index(op.f('ix_blog_medias_blog_id'), 'blog_medias', ['blog_id'], unique=False)
    op.create_index(op.f('ix_blog_medias_user_id'), 'blog_medias', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_blog_medias_user_id'), table_name='blog_medias')
    op.drop_index(op.f('ix_blog_medias_blog_id'), table_name='blog_medias')
    op.drop_table('blog_medias')
    # ### end Alembic commands ###
