"""remove featured image url

Revision ID: 1c5cb62d2492
Revises: f8cd3016dbf9
Create Date: 2026-03-26 08:31:10.529113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c5cb62d2492'
down_revision: Union[str, Sequence[str], None] = 'f8cd3016dbf9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blogs', 'featured_image_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('featured_image_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
