"""is domain verified field in users

Revision ID: 26f72660d2ba
Revises: aa68f0f73f5b
Create Date: 2026-03-25 13:44:34.611662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26f72660d2ba'
down_revision: Union[str, Sequence[str], None] = 'aa68f0f73f5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_domain_verified', sa.Boolean(), nullable=True))

    op.execute("UPDATE users SET is_domain_verified = false WHERE is_domain_verified IS NULL")

    op.alter_column('users', 'is_domain_verified', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_domain_verified')
    # ### end Alembic commands ###
