"""email logs id rename to log_id

Revision ID: 4457f2a48737
Revises: 57522e940673
Create Date: 2026-03-14 12:57:04.929678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4457f2a48737'
down_revision: Union[str, Sequence[str], None] = '57522e940673'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_logs', sa.Column('log_id', sa.Integer(), nullable=False))
    op.drop_column('email_logs', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_logs', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_column('email_logs', 'log_id')
    # ### end Alembic commands ###
