"""drop users email notifications

Revision ID: 484ff2aec353
Revises: e8a3c1d2f4b5
Create Date: 2026-04-12 08:58:54.398540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '484ff2aec353'
down_revision: Union[str, Sequence[str], None] = 'e8a3c1d2f4b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blog_medias', 'media_type')
    op.drop_index(op.f('uq_users_verified_custom_domain_lower'), table_name='users', postgresql_where='((custom_domain IS NOT NULL) AND (is_domain_verified IS TRUE))')
    op.drop_column('users', 'email_notifications')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email_notifications', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.create_index(op.f('uq_users_verified_custom_domain_lower'), 'users', [sa.literal_column('lower(custom_domain::text)')], unique=True, postgresql_where='((custom_domain IS NOT NULL) AND (is_domain_verified IS TRUE))')
    op.add_column('blog_medias', sa.Column('media_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
