"""views table

Revision ID: 5586895a5477
Revises: b467c89d3e81
Create Date: 2026-03-14 14:53:13.135343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5586895a5477'
down_revision: Union[str, Sequence[str], None] = 'b467c89d3e81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('views',
    sa.Column('view_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('blog_id', sa.Integer(), nullable=False),
    sa.Column('visitor_hash', sa.String(), nullable=False),
    sa.Column('visited_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['blog_id'], ['blogs.blog_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('view_id')
    )
    op.create_index(op.f('ix_views_blog_id'), 'views', ['blog_id'], unique=False)
    op.create_index(op.f('ix_views_user_id'), 'views', ['user_id'], unique=False)
    op.create_index(op.f('ix_views_visited_at'), 'views', ['visited_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_views_visited_at'), table_name='views')
    op.drop_index(op.f('ix_views_user_id'), table_name='views')
    op.drop_index(op.f('ix_views_blog_id'), table_name='views')
    op.drop_table('views')
    # ### end Alembic commands ###
