"""rename is_verified in users to email_verified

Revision ID: 8c1988974200
Revises: ad5b23199bb9
Create Date: 2026-03-27 17:34:32.755643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c1988974200'
down_revision: Union[str, Sequence[str], None] = 'ad5b23199bb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email_verified', sa.Boolean(), nullable=True))

    op.execute("UPDATE users SET email_verified = true")
    op.alter_column("users", "email_verified", nullable=False)

    op.drop_column('users', 'is_verified')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_verified', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('users', 'email_verified')
    # ### end Alembic commands ###
