"""add verification tick and remove footer gone

Revision ID: ad5b23199bb9
Revises: 1c5cb62d2492
Create Date: 2026-03-27 17:27:36.232854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad5b23199bb9'
down_revision: Union[str, Sequence[str], None] = '1c5cb62d2492'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('verification_tick', sa.Boolean(), nullable=True))

    op.execute("UPDATE users SET verification_tick = false")
    op.alter_column("users", "verification_tick", nullable=False)

    op.drop_column('users', 'remove_footer')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('remove_footer', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('users', 'verification_tick')
    # ### end Alembic commands ###
