"""finally add is_confirmed field to subscribers db

Revision ID: b18dc207988a
Revises: bb8ff3196d78
Create Date: 2026-03-13 19:01:30.093206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b18dc207988a'
down_revision: Union[str, Sequence[str], None] = 'bb8ff3196d78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscribers', sa.Column('is_confirmed', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_subscribers_is_confirmed'), 'subscribers', ['is_confirmed'], unique=False)

    op.execute("UPDATE subscribers SET is_confirmed = true WHERE is_confirmed IS NULL")
    op.alter_column("subscribers", "is_confirmed", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscribers_is_confirmed'), table_name='subscribers')
    op.drop_column('subscribers', 'is_confirmed')
    # ### end Alembic commands ###
