"""removed is_confirmed from subscribers

Revision ID: bb8ff3196d78
Revises: 4174dc409db9
Create Date: 2026-03-09 18:32:06.601224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb8ff3196d78'
down_revision: Union[str, Sequence[str], None] = '4174dc409db9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscribers', 'is_confirmed')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscribers', sa.Column('is_confirmed', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
