"""added subscribers table

Revision ID: cec47d70506f
Revises: 79ba26a44e54
Create Date: 2026-03-07 21:42:07.241919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cec47d70506f'
down_revision: Union[str, Sequence[str], None] = '79ba26a44e54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscribers',
    sa.Column('subscriber_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('subscribed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('unsubscribed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('subscriber_id')
    )
    op.create_index(op.f('ix_subscribers_subscribed_at'), 'subscribers', ['subscribed_at'], unique=False)
    op.create_index(op.f('ix_subscribers_unsubscribed_at'), 'subscribers', ['unsubscribed_at'], unique=False)
    op.create_index(op.f('ix_subscribers_user_id'), 'subscribers', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscribers_user_id'), table_name='subscribers')
    op.drop_index(op.f('ix_subscribers_unsubscribed_at'), table_name='subscribers')
    op.drop_index(op.f('ix_subscribers_subscribed_at'), table_name='subscribers')
    op.drop_table('subscribers')
    # ### end Alembic commands ###
