"""pro plans fields in users

Revision ID: e09ec46b498a
Revises: 5586895a5477
Create Date: 2026-03-16 18:24:53.851800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e09ec46b498a'
down_revision: Union[str, Sequence[str], None] = '5586895a5477'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('remove_footer', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('custom_domain', sa.String(), nullable=True))
    op.add_column('users', sa.Column('email_notifications', sa.Boolean(), nullable=True))

    op.execute("UPDATE users SET is_verified = false WHERE is_verified IS NULL")
    op.execute("UPDATE users SET remove_footer = false WHERE remove_footer IS NULL")
    op.execute("UPDATE users SET email_notifications = false WHERE email_notifications IS NULL")

    op.alter_column('users', 'is_verified', nullable=False)
    op.alter_column('users', 'remove_footer', nullable=False)
    op.alter_column('users', 'email_notifications', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email_notifications')
    op.drop_column('users', 'custom_domain')
    op.drop_column('users', 'remove_footer')
    op.drop_column('users', 'is_verified')
    # ### end Alembic commands ###
