"""is_confirmed field in subscribers

Revision ID: e79a2a83d4f9
Revises: cec47d70506f
Create Date: 2026-03-07 21:58:38.322203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e79a2a83d4f9'
down_revision: Union[str, Sequence[str], None] = 'cec47d70506f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscribers', sa.Column('is_confirmed', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscribers', 'is_confirmed')
    # ### end Alembic commands ###
