from sqlalchemy.orm import Session
from .. import models
from ..schemas import user, site


def public_site_out(db: Session, db_site: models.Site):
    data = {
        "subdomain": db_site.subdomain,
        "name": db_site.user.name if db_site.user else "",
        "site_name": db_site.site_name,
        "meta_title": db_site.meta_title or "",
        "meta_description": db_site.meta_description or "",
        "og_image_url": db_site.og_image_url,
        "template_id": db_site.template_id,
        "site_mode": db_site.site_mode,
        "color_theme": db_site.color_theme,
        "color_palette": db_site.color_palette,
        "font_family": db_site.font_family,
        "font_heading": db_site.font_heading,
        "font_content": db_site.font_content,
        "font_ui": db_site.font_ui,
        "button_style": db_site.button_style,
        "button_variant": db_site.button_variant,
        "navbar_alignment": db_site.navbar_alignment,
        "navbar_style": db_site.navbar_style,
        "navbar_enabled": db_site.navbar_enabled,
        "nav_menu_enabled": db_site.nav_menu_enabled,
        "nav_items": db_site.nav_items,
        "logo_url": db_site.logo_url,
        "logo_link": db_site.logo_link,
        "search_enabled": db_site.search_enabled,
        "theme_toggle_enabled": db_site.theme_toggle_enabled,
        "hero_title": db_site.hero_title,
        "hero_description": db_site.hero_description,
        "site_language": db_site.site_language,
        "og_locale": db_site.og_locale,
        "atom_enabled": db_site.atom_enabled,
        "rss_enabled": db_site.rss_enabled,
        "cta_heading": db_site.cta_heading,
        "cta_description": db_site.cta_description,
        "cta_button_text": db_site.cta_button_text,
        "cta_button_url": db_site.cta_button_url,
        "cta_show_on_posts": db_site.cta_show_on_posts,
        "cta_show_on_pages": db_site.cta_show_on_pages,
        "site_footer_enabled": db_site.site_footer_enabled,
        "footer_description": db_site.footer_description,
        "footer_columns": db_site.footer_columns,
        "footer_copyright": db_site.footer_copyright,
        "footer_socials_enabled": db_site.footer_socials_enabled,
        "footer_show_sitemap": db_site.footer_show_sitemap,
        "footer_show_rss": db_site.footer_show_rss,
        "footer_show_atom": db_site.footer_show_atom,
        "newsletter_headline": db_site.newsletter_headline,
        "newsletter_text": db_site.newsletter_text,
        "newsletter_disclaimer": db_site.newsletter_disclaimer,
        "newsletter_button_text": db_site.newsletter_button_text,
        "newsletter_show_near_header": db_site.newsletter_show_near_header,
        "newsletter_show_in_footer": db_site.newsletter_show_in_footer,
        "newsletter_webhook_url": db_site.newsletter_webhook_url,
        "favicon_url": db_site.favicon_url,
        "featured_blogs_enabled": db_site.featured_blogs_enabled,
        "featured_blog_ids": [str(bid) for bid in (db_site.featured_blog_ids or [])],
        "content_layout": db_site.content_layout,
        "show_preview_in_lists": db_site.show_preview_in_lists,
        "posts_per_page": db_site.posts_per_page,
        "pagination_type": db_site.pagination_type,
        "toc_enabled": db_site.toc_enabled,
        "custom_domain": db_site.custom_domain,
        "domain_status": db_site.domain_status,
        "umami_website_id": db_site.umami_website_id,
        "custom_head_code": db_site.custom_head_code,
        "custom_body_code": db_site.custom_body_code,
        "custom_css": db_site.custom_css,
        "seo_indexing_enabled": db_site.seo_indexing_enabled,
        "seo_noindex_categories": db_site.seo_noindex_categories,
        "seo_noindex_authors": db_site.seo_noindex_authors,
        "seo_noindex_pages": db_site.seo_noindex_pages,
        "seo_trailing_slash_listings": db_site.seo_trailing_slash_listings,
        "seo_trailing_slash_jsonld": db_site.seo_trailing_slash_jsonld,
        "seo_sitemap_enabled": db_site.seo_sitemap_enabled,
        "seo_robots_mode": db_site.seo_robots_mode,
        "seo_robots_custom": db_site.seo_robots_custom if db_site.seo_robots_mode == "custom" else None,
        "seo_llms_mode": db_site.seo_llms_mode,
        "seo_llms_custom": db_site.seo_llms_custom if db_site.seo_llms_mode == "custom" else None,
        "ga_measurement_id": db_site.ga_measurement_id,
        "adsense_publisher_id": db_site.adsense_publisher_id,
        "search_console_property": db_site.search_console_property,
        "search_console_verification_token": db_site.search_console_verification_token,
    }
    return site.PublicSite(**data)

def user_settings_out(db: Session, db_user: models.User, db_site: models.Site):
    data = {
        "user_id": db_user.user_id,
        "name": db_user.name,
        "subdomain": db_site.subdomain,
        "email": db_user.email,
        "google_id": db_user.google_id,
        "has_password": bool(db_user.password),
        "profile_image_url": db_user.profile_image_url,
        "site_name": db_site.site_name,
        "meta_title": db_site.meta_title,
        "meta_description": db_site.meta_description,
        "og_image_url": db_site.og_image_url,
        "template_id": db_site.template_id,
        "site_mode": db_site.site_mode,
        "color_theme": db_site.color_theme,
        "color_palette": db_site.color_palette,
        "font_family": db_site.font_family,
        "font_heading": db_site.font_heading,
        "font_content": db_site.font_content,
        "font_ui": db_site.font_ui,
        "button_style": db_site.button_style,
        "button_variant": db_site.button_variant,
        "navbar_alignment": db_site.navbar_alignment,
        "navbar_style": db_site.navbar_style,
        "navbar_enabled": db_site.navbar_enabled,
        "nav_menu_enabled": db_site.nav_menu_enabled,
        "nav_items": db_site.nav_items,
        "logo_url": db_site.logo_url,
        "logo_link": db_site.logo_link,
        "search_enabled": db_site.search_enabled,
        "theme_toggle_enabled": db_site.theme_toggle_enabled,
        "hero_title": db_site.hero_title,
        "hero_description": db_site.hero_description,
        "site_language": db_site.site_language,
        "og_locale": db_site.og_locale,
        "atom_enabled": db_site.atom_enabled,
        "rss_enabled": db_site.rss_enabled,
        "cta_heading": db_site.cta_heading,
        "cta_description": db_site.cta_description,
        "cta_button_text": db_site.cta_button_text,
        "cta_button_url": db_site.cta_button_url,
        "cta_show_on_posts": db_site.cta_show_on_posts,
        "cta_show_on_pages": db_site.cta_show_on_pages,
        "site_footer_enabled": db_site.site_footer_enabled,
        "footer_description": db_site.footer_description,
        "footer_columns": db_site.footer_columns,
        "footer_copyright": db_site.footer_copyright,
        "footer_socials_enabled": db_site.footer_socials_enabled,
        "footer_show_sitemap": db_site.footer_show_sitemap,
        "footer_show_rss": db_site.footer_show_rss,
        "footer_show_atom": db_site.footer_show_atom,
        "newsletter_headline": db_site.newsletter_headline,
        "newsletter_text": db_site.newsletter_text,
        "newsletter_disclaimer": db_site.newsletter_disclaimer,
        "newsletter_button_text": db_site.newsletter_button_text,
        "newsletter_show_near_header": db_site.newsletter_show_near_header,
        "newsletter_show_in_footer": db_site.newsletter_show_in_footer,
        "newsletter_webhook_url": db_site.newsletter_webhook_url,
        "newsletter_webhook_token": db_site.newsletter_webhook_token,
        "is_admin": False,  # handled downstream if needed
        "favicon_url": db_site.favicon_url,
        "featured_blogs_enabled": db_site.featured_blogs_enabled,
        "featured_blog_ids": [str(bid) for bid in (db_site.featured_blog_ids or [])],
        "custom_domain": db_site.custom_domain,
        "content_layout": db_site.content_layout,
        "show_preview_in_lists": db_site.show_preview_in_lists,
        "posts_per_page": db_site.posts_per_page,
        "pagination_type": db_site.pagination_type,
        "toc_enabled": db_site.toc_enabled,
        "domain_status": db_site.domain_status,
        "custom_head_code": db_site.custom_head_code,
        "custom_body_code": db_site.custom_body_code,
        "custom_css": db_site.custom_css,
        "seo_indexing_enabled": db_site.seo_indexing_enabled,
        "seo_noindex_categories": db_site.seo_noindex_categories,
        "seo_noindex_authors": db_site.seo_noindex_authors,
        "seo_noindex_pages": db_site.seo_noindex_pages,
        "seo_trailing_slash_listings": db_site.seo_trailing_slash_listings,
        "seo_trailing_slash_jsonld": db_site.seo_trailing_slash_jsonld,
        "seo_sitemap_enabled": db_site.seo_sitemap_enabled,
        "seo_robots_mode": db_site.seo_robots_mode,
        "seo_robots_custom": db_site.seo_robots_custom if db_site.seo_robots_mode == "custom" else None,
        "seo_llms_mode": db_site.seo_llms_mode,
        "seo_llms_custom": db_site.seo_llms_custom if db_site.seo_llms_mode == "custom" else None,
        "ga_measurement_id": db_site.ga_measurement_id,
        "adsense_publisher_id": db_site.adsense_publisher_id,
        "search_console_property": db_site.search_console_property,
        "search_console_verification_token": db_site.search_console_verification_token,
    }
    
    # check if user is admin
    from .admin import is_admin_email
    data["is_admin"] = is_admin_email(db_user.email)
    
    return user.UserSettings(**data)
